#!/usr/bin/env python3
"""長期トークンを再延長して `.env` を上書き更新する.

長期トークン (約60日有効) を `fb_exchange_token` パラメータに渡すと、
新たに約60日有効な長期トークンが発行される (Graph API の挙動).
これにより、トークンが切れる前に定期実行すれば永続運用が可能になる.

呼び出し方:
    # 残日数チェック付き (デフォルト): 14日未満なら更新、そうでなければスキップ
    python3 refresh_token.py

    # 強制更新 (残日数によらず必ず更新)
    python3 refresh_token.py --force

    # 終了コード:
    #   0 = 更新した or 更新不要 (まだ余裕あり)
    #   1 = エラー (ネットワーク, secret不一致, トークン失効など)

Exit code 0 で更新した場合は stdout に `REFRESHED expires=<ISO>` を出力.
スキップ時は `SKIPPED days_left=<N>` を出力.
"""
import argparse
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import Request, urlopen
from urllib.error import HTTPError

GRAPH = "https://graph.facebook.com/v21.0"
ENV_PATH = Path(__file__).resolve().parent / ".env"
REFRESH_THRESHOLD_DAYS = 14  # 残り日数がこれ未満なら更新


def load_env(path):
    if not path.exists():
        sys.exit(f"ERROR: {path} がありません")
    env = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        env[k.strip()] = v.strip()
    return env


def write_env(path, env_dict):
    lines = ["# Generated by refresh_token.py (auto-managed)"]
    for k in ("FB_APP_ID", "FB_APP_SECRET", "IG_USER_ID", "IG_ACCESS_TOKEN", "IG_TOKEN_EXPIRES_AT"):
        if k in env_dict:
            lines.append(f"{k}={env_dict[k]}")
    # 他に存在するキー (FB_PAGE_ID 等) があれば末尾に保持
    for k, v in env_dict.items():
        if k not in ("FB_APP_ID", "FB_APP_SECRET", "IG_USER_ID", "IG_ACCESS_TOKEN", "IG_TOKEN_EXPIRES_AT"):
            lines.append(f"{k}={v}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    path.chmod(0o600)


def http_get(url, params):
    full = f"{url}?{urlencode(params)}"
    try:
        with urlopen(Request(full), timeout=30) as resp:
            return json.loads(resp.read().decode())
    except HTTPError as e:
        body = e.read().decode(errors="replace")
        sys.exit(f"HTTP {e.code}: {body}")


def days_until(iso_str):
    dt = datetime.fromisoformat(iso_str)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    delta = dt - datetime.now(timezone.utc)
    return delta.total_seconds() / 86400.0


def mask(t):
    if not t or len(t) < 12:
        return "***"
    return f"{t[:6]}...{t[-4:]} (len={len(t)})"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--force", action="store_true", help="残日数に関係なく必ず更新")
    parser.add_argument("--threshold-days", type=int, default=REFRESH_THRESHOLD_DAYS,
                        help=f"このN日未満なら更新 (default: {REFRESH_THRESHOLD_DAYS})")
    args = parser.parse_args()

    env = load_env(ENV_PATH)
    for k in ("FB_APP_ID", "FB_APP_SECRET", "IG_ACCESS_TOKEN"):
        if k not in env:
            sys.exit(f"ERROR: .env に {k} がありません")

    current_token = env["IG_ACCESS_TOKEN"]
    expires_iso = env.get("IG_TOKEN_EXPIRES_AT", "")
    if expires_iso and not args.force:
        days_left = days_until(expires_iso)
        if days_left >= args.threshold_days:
            print(f"SKIPPED days_left={days_left:.1f} (>= {args.threshold_days})")
            return 0
        print(f"[1/2] 残り {days_left:.1f} 日 (閾値 {args.threshold_days} 日未満) -> 更新します")
    else:
        print("[1/2] 強制更新モード" if args.force else "[1/2] 期限不明 -> 更新します")

    # 長期トークンを fb_exchange_token に渡して再延長
    data = http_get(
        f"{GRAPH}/oauth/access_token",
        {
            "grant_type": "fb_exchange_token",
            "client_id": env["FB_APP_ID"],
            "client_secret": env["FB_APP_SECRET"],
            "fb_exchange_token": current_token,
        },
    )
    new_token = data.get("access_token")
    expires_in = data.get("expires_in")
    if not new_token:
        sys.exit(f"ERROR: access_token が応答に無い: {data}")

    if expires_in:
        new_expires = datetime.now(timezone.utc) + timedelta(seconds=int(expires_in))
    else:
        new_expires = datetime.now(timezone.utc) + timedelta(days=60)
    new_expires_iso = new_expires.replace(microsecond=0).isoformat()

    print(f"  new token: {mask(new_token)}")
    print(f"  expires:   {new_expires_iso} (~{(expires_in or 0)//86400} 日)")

    print("[2/2] .env 更新 ...")
    env["IG_ACCESS_TOKEN"] = new_token
    env["IG_TOKEN_EXPIRES_AT"] = new_expires_iso
    write_env(ENV_PATH, env)
    print(f"REFRESHED expires={new_expires_iso}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
